version: "3"

services:
  car:
    image: maven:3.6.0-alpine
    container_name: "car-service"
    environment:
      DB_URL: jdbc:mysql://db:3306/default
      DB_USER: mysql
      DB_PASS: mysql
    volumes:
      - ./target:/usr/src/target
    command: java -jar /usr/src/target/car-service-1.0-SNAPSHOT.jar
    ports:
      - 9100:8080
    depends_on:
      - db

  db:
    container_name: "wildfly_database"
    image: "mysql:latest"
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_VERSION=8.0.15
    volumes:
      - ./volumes/db/init/:/docker-entrypoint-initdb.d/ # init database
      - ./volumes/db/data/:/var/lib/mysql/              # data storage
    ports:
      - "3100:3306"     #Default

