version: "3"

services:
  car:
    container_name: "car-service"
    build: .
    image: yoksar/car-service
    environment:
      DB_URL: jdbc:mysql://192.168.178.24:9010/projectdb
      DB_USER: mysql
      DB_PASS: mysql
    ports:
      - 9100:8080
    restart: unless-stopped

